apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gdxl
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0053-tenant/tkrw-pr712-0075-0053-app/devfile-sample-gdxl@sha256:da95955cc69eedfcad4bdf4297b709093e1b177041f9ad8651daa2a32653ae25
        name: my-nodejs
        resources: {}
status: {}
